// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muvoyzxwigwgznnocqqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11dm95enh3aWd3Z3pubm9jcXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzAyMTUsImV4cCI6MjA2OTM0NjIxNX0.ylgyNtoIY71ACK2mJF13nVxV_93Cu7D40erTGSwz78M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});